project:
  type: book
  resources:
    - assets/

execute:
  freeze: true

jupyter:
  kernelspec:
    name: ai-patterns-venv
    language: python
    display_name: "AI Patterns venv"

book:
  title: "AI Design Patterns for GLAM"
  author: "Daniel van Strien"
  date: today
  chapters:
    - index.qmd
    # - intro.qmd # TODO
    - part: "Beyond Chat Interfaces to Collections?"
      # chapters:
      #   - discovery/boring-ai.qmd

    - part: "Design Patterns"
      chapters:
        - patterns/what-is-an-ai-pattern.qmd

    - part: "Structured Information Extraction"
      chapters:
        - patterns/structured-generation/intro.qmd
        - patterns/structured-generation/vlm-structured-generation.qmd
    #    - patterns/structured-generation/advisor-index-cards.ipynb
    # - part: "Technology Evaluations"
    #   chapters:
    #     - ocr-evaluation.qmd
    # - references.qmd
    # - part: "Appendices"
    #   chapters:
    #     - appendix/assessment-form.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    search: true
  pdf:
    documentclass: scrreprt

glossary:
  path: glossary.yml
  popup: hover
  show: true
