project:
  type: book
  resources:
    - assets/

execute:
  freeze: true

jupyter:
  python:
    path: .venv/bin/python
  kernelspec:
    name: ai-patterns-venv
    language: python
    display_name: "AI Patterns venv"

book:
  title: "AI Design Patterns for Information Professionals"
  author: "Daniel van Strien"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Beyond Chat Interfaces"
      chapters:
        - discovery/boring-ai.qmd
        - discovery/beyond-chatbots.qmd

    - part: "Design Patterns"
      chapters:
        - patterns/what-is-an-ai-pattern.qmd

    - part: "Structured Information Extraction"
      chapters:
        - patterns/structured-generation/intro.qmd
        - patterns/structured-generation/vlm-structured-generation.qmd
    #    - patterns/structured-generation/advisor-index-cards.ipynb

    - part: "More Patterns"
      chapters:
        - patterns/vlm-ocr.qmd
        - patterns/semantic-search.qmd
        - patterns/distillation.qmd
        - patterns/agentic-workflows.qmd

    - part: "Evaluating AI Outputs"
      chapters:
        - evaluating-intro.qmd
        - evaluating-ai-outputs.qmd
    - part: "Infrastructure"
      chapters:
        - infrastructure/hardware-considerations.qmd
    - part: "Appendices"
      chapters:
        - appendix/assessment-form.qmd
    - glossary-page.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    search: true
  # pdf:
  #   documentclass: scrreprt

glossary:
  path: glossary.yml
  popup: click
  show: true
